### PR TITLE
Add function to return UTC time as ISO string

### PR DESCRIPTION
**Pull request by tomekc**

### CODE REVIEW

**Review by kglusinski — APPROVED** [review]

**Comment by kglusinski** [comment]
I agree with Sebastian. Accept but I don't think either we need it or we should use it.

**Comment by tomekc** [comment]
> I agree with Sebastian. Accept but I don't think either we need it or we should use it.

Not trying to push it forcibly, but what if:

* someone forgot that we want (if we want :) ) to use UTC ttimezone in DB
* someone is not sure if use nanoseconds or not?

There are multiple decisions here, but I am open to be wrong.

**Comment by mazxaxz** [comment]
> someone forgot that we want (if we want :) ) to use UTC ttimezone in DB

i dont think it is a concern of a global library (which imo is a one unnecessary wrapper), these time standards should be written in some place like confluence and every app should implement them

> someone is not sure if use nanoseconds or not?

same as above, there should be global page with standards

+ everything in these repo excluding `envs` and `logging` is completely useless and it should be removed, but thats just my opinion

**Comment by mtripi** [comment]
maybe it's a good time to finally get rid of this `utils` repository?

**Comment by mazxaxz** [comment]
we can mark it as obsolete and establish some migration deadline

**Comment by tomekc** [comment]
So I will close that PR. We may think about some housekeeping. Logging became obsolete with introduction of `zerolog`, probably `envs` is most useful as of now.

**Pull request closed without merging**
